### ISSUE TITLE
alembic_utils does not work with Redshift Dialect.

### ISSUE THREAD

**Issue by mfdickerson** [olirice/alembic_utils#123]
alembic_utils does not appear to work with the Redshift dialect, and attempts a number of operations that are not supported by Redshift.

- While attempting to autogenerate migrations that involve changing a materialized view, I get an error:
```
sqlalchemy.exc.NotSupportedError: (psycopg2.errors.FeatureNotSupported) SQL command "ROLLBACK TO SAVEPOINT sa_savepoint_2" not supported.

[SQL: ROLLBACK TO SAVEPOINT sa_savepoint_2]
(Background on this error at: https://sqlalche.me/e/14/tw8g)
```
because savepoints are not supported by Redshift.

- Additionally, after manually crafting a revision, the upgrade failed with because it attempted to add `WITH DATA` to the end of the materialized view SQL. I don't believe that syntax is supported by Redshift.

**Comment by olirice** [comment]
Redshift was forked from postgres in version ~8 and hasn't kept pace with the dialect or feature support due to differing goals.

alembic_utils makes heavy use of modern postgres features that aren't supported by redshift (like savepoints). for that reason, there's no clear path to support redshift and it isn't an intended goal of the project.

if you'd like to continue using this project for your redshift migrations I'd suggest using postgres locally to create the migrations. even then, you may run into cases where the rendered migration is not supported in redshift though, so milage may vary
