### ISSUE TITLE
Be compatible with `sqlalchemy_utils.create_view`?

### ISSUE THREAD

**Issue by jorgecarleitao** [olirice/alembic_utils#14]
Currently, there seems to be two independent ways of working with views:

* this package
* `sqlalchemy_utils.create_view`

They serve a slightly different purpose: one allows the view to be used on an ORM, the other allows views to be maintained declaratively with alembic.

They also have tradeoffs:

* `sqlalchemy_utils.create_view` supports generic expressions, which makes it more generic
* `sqlalchemy_utils.create_view` does not work with alembic

Which bears the question: wouldn't it make sense to support the `sqlalchemy_utils` construct?

Specifically, something like

```python
# models.py
from sqlalchemy.ext.declarative import declarative_base

from sqlalchemy import Column, Integer, String, select
from sqlalchemy_utils import create_view

Base = declarative_base()


class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True)
    name = Column(String(50))
    name1 = Column(String(50))


class MyView(Base):
    __table__ = create_view("my_view", select([User.name]).select_from(User.__table__), Base.metadata)
```

and use this package to track the `MyView` with alembic?

**Comment by olirice** [comment]
I agree that it would be be nice to automatically produce a `sqlalchemy.Table` object from a PGView, but there are some complications to making that happen.

alembic_utils has first class support for raw sql. In contrast, `sqlalchemy_utils.views.create_view` works exclusively with the sqlalchemy query builder. Since `create_view` uses the query builder, its able to extract a list of column names and types without relying on an active postgres connection. That is not ~~possible~~ practical with raw sql.

Additionally, registering a view with a `Metadata` instance as a `Table` will cause `alembic` to try to migrate it as as a table, resulting in incorrect `--autogenerate` output. That can be overcome with [this recipe](https://alembic.sqlalchemy.org/en/latest/cookbook.html#don-t-emit-create-table-statements-for-views) but it raises the barrier to entry.

However, given that you are using the query builder, you can get the functionality you're looking for like this:

```python
# models.py
from alembic_utils.pg_view import PGView

from sqlalchemy import Column, Integer, String, select
from sqlalchemy.ext.declarative import declarative_base

from sqlalchemy_utils.view import create_table_from_selectable
from sqlalchemy.dialects import postgresql

Base = declarative_base()

class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True)
    name = Column(String(50))
    name1 = Column(String(50))

# define the query separately
MY_VIEW_NAME = "my_view"
MY_VIEW_SELECTABLE = select([User.name]).select_from(User.__table__), Base.metadata)

# compile the query to raw sql using the postgres dialect to produce the `PGView`
MyViewAlembic = PGView(
    schema="public",
    signature=MY_VIEW_NAME,
    definition=str(MY_VIEW_SELECTABLE.compile(dialect=postgresql.dialect()))
)

# use `create_table_from_selectable` to convert the query to a `sqlalchemy.Table` without
# emitting a `CREATE VIEW` statement 
class MyView(Base):
    __table__ = create_table_from_selectable(
        name=MY_VIEW_NAME,
        selectable=MY_VIEW_SELECTABLE
    )
```
you can then use `MyView` for queries and and `MyViewAlembic` for migrations. 


If you were using raw sql instead of the query builder, you can accomplish the same thing, but need to define the table's interface manually i.e.

```python
# models.py
from alembic_utils.pg_view import PGView

from sqlalchemy import Column, Integer, String, select
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class MyView(Base):
    __table__ =     __table__ = Table(
        "my_view",
        Base.metadata,
        Column("id", Integer, primary_key=True),
        Column("name", String),
        info={"is_view": True},
        schema="public",
    )


MyViewAlembic = PGView(
    schema="public",
    signature="my_view",
    definition="select id, name from user"
)
```
Ref #6

**Comment by jorgecarleitao** [comment]
@olirice thank you so much for the prompt response and for its content 💯. Really great response. I am closing as resolved. 👍

**Comment by jorgecarleitao** [comment]
Any reason for using `create_table_from_selectable` instead of `create_view`?

> Additionally, registering a view with a Metadata instance as a Table will cause alembic to try to migrate it as as a table, resulting in incorrect --autogenerate output. That can be overcome with this recipe but it raises the barrier to entry.

I can't reproduce this behavior. Specifically, in the example I gave, running 

```bash
alembic revision --autogenerate -m "Test"
```

does not cause the view to be picked up by alembic (this is the whole reason `sqlalchemy_utils` is not sufficient to manage views).

**Comment by olirice** [comment]
`create_table` calls `create_table_from_selectable` [ref](https://github.com/kvesteri/sqlalchemy-utils/blob/c4e18ffcfb558a6142f90cf018cfea80ea194018/sqlalchemy_utils/view.py#L155)

In addition to converting a selectable into a `Table`, `create_view` [registers event listeners](https://github.com/kvesteri/sqlalchemy-utils/blob/c4e18ffcfb558a6142f90cf018cfea80ea194018/sqlalchemy_utils/view.py#L163) to emit DDL statements when the view is created in the database. Since you're using alembic for migrations, that isn't needed.

> I can't reproduce this behavior

You're right, I was mistaken that registering the view as a table on metadata under alembic's control would cause it to show up as a table in `--autogenerate` migrations. But that's a good thing.
